---
- name: Create node_exporter user
  user:
    name: nodeexp
    system: yes
    shell: /usr/sbin/nologin

- name: Download node_exporter binary
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/
    remote_src: yes

- name: Symlink node_exporter
  file:
    src: /opt/node_exporter-1.7.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    state: link

- name: Create systemd service for node_exporter
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=nodeexp
      ExecStart=/usr/local/bin/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Lancement manuel de node_exporter (Docker workaround)
  shell: "nohup /usr/local/bin/node_exporter > /var/log/node_exporter.log 2>&1 &"
  args:
    creates: /var/log/node_exporter.log